### ISSUE TITLE
Pin Existing Entry

### ISSUE THREAD

**Issue by ColleenMa** [EndianTribe/Reconcile-Issues-Tracker-Public#12]
Right now I can only pin entries on creation. I should be able to go back and pin pre-existing entries. What if I forget to pin an entry? What if an entry becomes important later? Users need this option.

**Comment by EndianTribe** [comment]
The pin button at the top right hand corner of the creation screen pins the screen such that after an entry is added, the screen does not go away, thereby allowing fast entry of multiple journal entry items.

The ledger is always sorted by descending time order by design. At the moment I do not have any plans to implement any other sort order as doing so would defeat the purpose of the ledger. On a ledger, the user in general does not care about each individual journal entry item after it is added as the user is most concerned about the total amount outstanding. In rare cases where a user may wish to revisit a previous journal entry item, the user can use the search function.
